Added Housekeeping function, added timebased renew

diff --git a/eve4pve-barc b/eve4pve-barc
--- a/eve4pve-barc
+++ b/eve4pve-barc
@@ -4,7 +4,7 @@
 # Author: Daniele Corsini <daniele.corsini@enterpriseve.com>
 #         Bastian Mäuser <bma@netz.org>        
 
-declare -r VERSION=0.2.1b-renew
+declare -r VERSION=0.2.2-renew
 declare -r NAME=$(basename "$0")
 declare -r PROGNAME=${NAME%.*}
 
@@ -30,10 +30,11 @@ declare opt_vm_ids=''
 declare opt_cksum=true
 declare opt_ckmethod="sha1sum"
 declare opt_compress="none"
-declare opt_compressthreads=1
+declare opt_compressthreads=2
 declare opt_qemu_freeze=true
+declare opt_renew #=0
+declare opt_retain
 declare -i opt_keep #=0
-declare -i opt_renew #=0
 declare -i opt_iothreads=10
 declare -i opt_syslog=0
 declare -i opt_debug=0
@@ -60,6 +61,13 @@ declare -i -g exportok
 declare -i -g bytecount
 declare -g startts
 declare -g endts
+
+
+declare -r renum='^[0-9]+$'
+declare -r retime='([0-9]+)([d,w])$'
+declare -r reimg='^.*\/([0-9]+)([a-zA-Z-]+)\.(.*)\.(diff|img).?(.*)?'
+declare -r redateex='^([0-9]{4})([0-9]{2})([0-9]{2})([0-9]{2})([0-9]{2})([0-9]{2})$'
+
 
 function map_vmids_to_host(){
     for node in $(/usr/bin/pvecm nodes | tail +5 | tr -s ' ' | cut -d' ' -f 4)
@@ -134,12 +142,17 @@ Options:
     --path               Path destination backup
     --keep               Specify the number of backup which should will keep, (default: 1)
     --renew              Specify how many diffs may accumulate, until a full Backup is issued
+                         --renew=10 for keeping 10 Diffs until making a new full export
+                         --renew=7d for making diffs up to 7 days, until making a new full export
+    --retain             Specify how many Backups should be kept, timewise (default: infinite - if unset, nothing is ever deleted)
+                         --retain=30d to keep Backups for 30 days. If the Point in time matches a diff, 
+                         if keeps all previous diffs and the preceding full image to ensure possibility to restore data
     --cksum              Store checksums for snapshot validation (default: true)
     --ckmethod           Method used for Checksumming [m5sum, sha1sum, sha224sum, sha384sum, sha512sum] (default: sha1sum)
     --qemu-freeze        Issue fsfreeze-freeze prio snapshotting and fsfreeze-thaw after snapshot completion (default: true)
     --iothreads          Specify number of IO threads for exporting (default: 10)
     --compress           Specify compression method [none,gzip,bzip2,pigz] (default: none)
-    --compressthreads    Specify compression threads for pigz (default: 1)
+    --compressthreads    Specify compression threads for pigz (default: 2)
     --script             Use specified hook script
                          E.g. /usr/share/doc/$PROGNAME/examples/script-hook.sh
     --syslog             Write messages into the system log
@@ -219,7 +232,7 @@ function parse_opts(){
     local args
     args=$(getopt \
            --options '' \
-           --longoptions=path:,vmid:,label:,keep:,renew:,cksum:,ckmethod:,iothreads:,compress:,compressthreads:,mail: \
+           --longoptions=path:,vmid:,label:,keep:,renew:,retain:,cksum:,ckmethod:,iothreads:,compress:,compressthreads:,mail: \
            --longoptions=script:,syslog,debug,dry-run,unprotect-snap,qemu-freeze \
            --name "$PROGNAME" \
            -- "$@") \
@@ -232,7 +245,8 @@ function parse_opts(){
         --vmid) opt_vm_ids=$2; shift 2;;
         --label) opt_label="$2"; shift 2;;
         --keep) opt_keep=$2; shift 2;;
-        --renew) opt_renew=$2; shift 2;;
+        --renew) opt_renew="$2"; shift 2;;
+        --retain) opt_retain="$2"; shift 2;;
         --cksum) opt_cksum=$2; shift 2;;
         --ckmethod) opt_ckmethod=$2; shift 2;;
         --iothreads) opt_iothreads=$2; shift 2;;
@@ -602,6 +616,7 @@ function backup(){
         local image_spec
         local current_snap
         local backup_file
+        local backup_file_present
         local latest_snap
         local compress
 
@@ -633,11 +648,10 @@ function backup(){
             #obey renew policy
             local diffcount=0
             local renew=false
-            if [[ "$opt_renew" -gt 0 ]]; then
-                #regex='^.*\.(.*)$'
-                regex='^.*\/([0-9]+)([a-zA-Z-]+)\.(.*)\.(diff|img).?(.*)?'
+            #count mode (accumulate diff's until they exceed a given number --renew=X)
+            if [[ $opt_renew =~ $renum ]] && [[ "$opt_renew" -gt 0 ]]; then 
                 for backup_files_present in $(ls -r $path_backup/*$suffix_backup_file{$EXT_DIFF,$EXT_IMAGE}{.gz,.bz2,} 2>/dev/null); do
-                    if [[ "$backup_files_present" =~ $regex ]]; then
+                    if [[ "$backup_files_present" =~ $reimg ]]; then
                         ext=${BASH_REMATCH[4]}
                         if [ "$ext" == 'diff' ]; then
                             diffcount=$((diffcount+1))
@@ -651,8 +665,35 @@ function backup(){
                         break;
                     fi
                 done
+            #time mode (accumulate diff's until given time has passed --renew=Xd)
+            elif [[ $opt_renew =~ $retime ]]; then
+                local factor=86400    #tbd: support d, w, m
+                maxage=$((${BASH_REMATCH[1]}*$factor))
+                for backup_files_present in $(ls -r $path_backup/*$suffix_backup_file{$EXT_DIFF,$EXT_IMAGE}{.gz,.bz2,} 2>/dev/null); do
+                    if [[ "$backup_files_present" =~ $reimg ]]; then
+                        ext=${BASH_REMATCH[4]}
+                        ts=${BASH_REMATCH[1]}
+                        if [[ $ts =~ $redateex ]]; then
+                            fdate=$((`date --date "${BASH_REMATCH[1]}/${BASH_REMATCH[2]}/${BASH_REMATCH[3]} ${BASH_REMATCH[4]}:${BASH_REMATCH[5]}:${BASH_REMATCH[6]}" +%s`))
+                        else
+                            rc=70
+                            break;
+                        fi
+                        age=$((`date +"%s"`-$fdate))
+                        echo "TS: $ts $ext $fdate $age $backup_files_present"
+                        if [ "$ext" == 'img' ]; then
+                            echo "Full found, age ($age), maxage ($maxage)"
+                            if [[ $age -ge $maxage ]]; then
+                                echo "Age of most recent full exceeds maxage"
+                                renew=true
+                                break;
+                            fi
+                            break;
+                        fi
+                    fi
+                done
             fi
-            #exit
+
             #check exist initial export
             if ! exist_file "$path_backup/*$suffix_backup_file$EXT_IMAGE*"; then
                 #initial export not exist            
@@ -839,10 +880,17 @@ function backup(){
         vmok=$((vmok+1))
 
         # If no renew policy is set, do the merge magic
-        if [[ ! "$opt_renew" -gt 0 ]]; then
+        if [[ "$opt_renew" == "" ]]; then
             log info "VM $vm_id - -------- Merge diff file --------"
             merge_diff_backup
         fi
+
+        # If renew policy is set, do some housekeeping
+        if ! [[ "$opt_renew" == "" ]] && [[ $opt_retain =~ $retime ]]; then
+            log info "VM $vm_id - -------- Housekeeping --------"
+            housekeeping
+        fi
+
     done
 
     vm_id=0
@@ -865,6 +913,40 @@ function sum_size_file(){
     echo $((sumbytes+$(ls -l "$1" | awk '{print $5}')))
 }
 
+function housekeeping() {
+    local image=''
+    local keepfile=true
+    local imgreached=false
+    local factor=86400 #tbd
+    [[ $opt_retain =~ $retime ]]
+    maxage=$((${BASH_REMATCH[1]}*$factor))
+    for image in $(ls -r $path_backup/*{$EXT_DIFF,$EXT_IMAGE}{.gz,.bz2,} 2>/dev/null); do
+        if [[ "$image" =~ $reimg ]]; then
+            ext=${BASH_REMATCH[4]}
+            ts=${BASH_REMATCH[1]}
+            if [[ $ts =~ $redateex ]]; then
+                fdate=$((`date --date "${BASH_REMATCH[1]}/${BASH_REMATCH[2]}/${BASH_REMATCH[3]} ${BASH_REMATCH[4]}:${BASH_REMATCH[5]}:${BASH_REMATCH[6]}" +%s`))
+            else
+                rc=10
+                log error "Houskeeping Error"
+                break;
+            fi
+            age=$((`date +"%s"`-$fdate))
+            if [[ $age -ge $maxage ]]; then
+                if [[ ".$ext" == "$EXT_IMAGE" ]]; then
+                    imgreached=true
+                fi
+            fi
+            if ! [[ "$keepfile" == true ]]; then
+                log info "VM $vm_id - Houskeeping deleting: $image"
+                do_run "unlink $image"
+            fi
+            if [[ "$imgreached" == true ]]; then 
+                keepfile=false
+            fi
+        fi
+    done
+}
 
 function merge_diff_backup(){
     #loop all image
@@ -1040,8 +1122,8 @@ function restore(){
         startts=$(date +%s)
 
         #Create actionplan
-        regex='^([0-9]+)([a-zA-Z-]+)\.(.*)\.(diff|img).?(.*)?'
-        [[ "$image" =~ $regex ]]
+        #regex='^([0-9]+)([a-zA-Z-]+)\.(.*)\.(diff|img).?(.*)?'
+        [[ "$image" =~ $reimg ]]
         searchdisk=${BASH_REMATCH[3]}
         local inchain=false
         local -a plan
@@ -1050,7 +1132,7 @@ function restore(){
                 inchain=true
             fi
             if [ "$inchain" == true ]; then
-                [[ "$backup_files" =~ $regex ]]
+                [[ "$backup_files" =~ $reimg ]]
                 founddisk=${BASH_REMATCH[3]}
                 ext=${BASH_REMATCH[4]}
                 if [ "$founddisk" == "$searchdisk" ]; then
@@ -1066,7 +1148,7 @@ function restore(){
         local backup=''
         for backup in "${plan[@]}"; do
             regex='^([0-9]+)([a-zA-Z-]+)\.(.*)\.(diff|img).?(.*)?'
-            [[ "$backup" =~ $regex ]]
+            [[ "$backup" =~ $reimg ]]
             local timestamp_snap; timestamp_snap=${BASH_REMATCH[1]}
             local ext; ext=${BASH_REMATCH[4]}
             local cext; cext=${BASH_REMATCH[5]}
